app2021/urls.py
from django.urls import path
from . import views

app_name = 'task_app'


urlpatterns = [
    path('', views.main, name='main'),
    path('materials/', views.all_materials, name='all_materials'),
]

vlad2021/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app2021.urls', namespace='app2021')),
]

app2021/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class Storage(models.Model):
    name = JSONField()

app2021/forms.py
from django import forms


class InputForm(forms.Form):
    name = forms.CharField(max_length=255)

app2021/views.py
from django.shortcuts import render
from django.shortcuts import redirect
import json
from . import forms
from .models import Storage


def main(request):
    if request.method == 'POST':
        form = forms.InputForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data['name']
            name = json.dumps(cd, ensure_ascii=False)
            new_entry = Storage(name=name)
            new_entry.save()
            return redirect('/')
    else:
        try:
            num_of_the_latest_material = Storage.objects.latest('id')
            counter = num_of_the_latest_material.id
        except:
            counter = ''
        form = forms.InputForm()
        return render(request,
                      'main.html',
                      {'form': form, 'num_of_the_latest_materaial': counter},
                      )


def all_materials(request):
    materials = Storage.objects.all()
    return render(request,
                  'all_materials.html',
                  {'materials': materials})

app2021/templates/all_materials.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

{% block title %} Material list {% endblock %}

{% block content %}
    <h1>My Materials</h1>
    {% for material in materials %}
        <h2>{{ material.name }}</h2>
    {% endfor %}
{% endblock %}

app2021/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

{% block title %} Input {{num_of_the_latest_materaial}} {% endblock %}

{% block content %}
        <form action="." method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Input">
        </form>
        <a href="{% url 'task_app:all_materials' %}">show all materials</a>

{% endblock %}